title: Muhammad Arfanul Aziz # your name (or website title) here
logo: "images/profile picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I’m Data Science & Analytics Enthusiast. Driven by improving people’s quality of life through the practical implementation of data driven solutions in technical & business studies. 
  <br><br>
  Strong problem solving and critical thinking capacities, proven by the successful completion of numerous research and technical studies in diverse areas. 
  <br><br>
  <a href="https://www.linkedin.com/in/muhammad-arfanul-aziz/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 207665061 # your Google Analytics tracking ID here
